# fly.toml app configuration file generated for verification-form on 2024-08-10T01:44:07+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'verification-form'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
